version: '3.8'

services:
  ngnix-gateway:
    image: nginx:alpine
    ports:
      - "3055:80"
    volumes:
      - ./ngnix/ngnix.conf:/etc/nginx/nginx.conf
    depends_on:
      - sv-auth
      - sv-users
      - sv-orders
    networks:
      - microservices-net

  #contenedor de microservicio de autentificacion
  sv-auth:
    build: ./sv-auth
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis-cache
      - REDIS_PASSWORD=
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - redis-cache
      - postgres
    networks:
      - microservices-net

  #contenedor de microservicio de ordenes
  sv-orders:
    build: ./sv-orders
    ports:
      - "8082:8082"
    environment:
      - REDIS_HOST=redis-cache
      - REDIS_PASSWORD=
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - redis-cache
      - postgres
    networks:
      - microservices-net

  #contenedor de microservicio de usuarios
  sv-users:
    build: ./sv-users
    ports:
      - "8083:8083"
    environment:
      - REDIS_HOST=redis-cache
      - REDIS_PASSWORD=
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - redis-cache
      - postgres
    networks:
      - microservices-net

  redis-cache:
    image: redis:alpine
    ports:
      - "6380:6379"

    networks:
      - microservices-net

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db-microservices
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres_data:
