events{
    worker_connections 1024;
}

http {
   upstream auth_services {server sv-auth:8081; }
   upstream orders_services {server sv-orders:8082; }
   upstream users_services {server sv-users:8083; }
   
  server{
    listen 80;
    location /api/auth/ {
      proxy_pass http://auth_services/auth/;
      proxy_set_header Host $host;
    }
    location /api/orders/ {
      proxy_pass http://orders_services/orders/;
      proxy_set_header Host $host;
    }
    location /api/users/ {
      proxy_pass http://users_services/users/;
      proxy_set_header Host $host;
    }
  }

}